host: "0.0.0.0:33000"
servers:
  lobby:
    address: "127.0.0.1:30030"
  survival:
    address: "127.0.0.1:30031"
  creative:
    address: "127.0.0.1:30032"
  skyblock:
    address: "127.0.0.1:30033"
default_server: lobby
force_default_server: true
admin: "Elidragon"
server_reintergration_interval: 15
disable_builtin: true
serverlist_url: "https://servers.minetest.net"
serverlist_address: "zap.elidragon.com"
serverlist_name: "Elidragon v2 [alpha]"
serverlist_desc: "Alpha server for Elidragon v2. The server may reset anytime, so it is not recommended to make any progess yet. Expect crashes, restarts, downtime and limited functionality. Subgame: MineClone2. Uses multiserver by HimbeerserverDE."
serverlist_damage: true
serverlist_pvp: true
